vm.dirty_writeback_centisecs = 30000
vm.dirty_background_bytes = 67108864
vm.dirty_bytes = 268435456
vm.watermark_scale_factor = 125
vm.watermark_boost_factor = 0
vm.max_map_count = 2147483642
vm.vfs_cache_pressure = 50
vm.page-cluster = 1
vm.swappiness = 150
vm.laptop_mode = 0

kernel.sched_lib_name = com.sega., com.HoYoverse., com.miHoYo., com.activision., UnityMain, libunity.so, libfb.so
kernel.sched_lib_mask_force = 255
kernel.unprivileged_userns_clone = 1
kernel.core_pattern = /dev/null
kernel.kexec_load_disabled = 1
kernel.perf_event_paranoid = 2
kernel.dmesg_restrict = 1
kernel.kptr_restrict = 2
kernel.nmi_watchdog = 0

fs.xfs.xfssyncd_centisecs = 30000
fs.file-max = 2097152
fs.suid_dumpable = 0

net.ipv4.tcp_rmem = 4096 262144 16777216
net.ipv4.tcp_wmem = 4096 131072 6194136
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.udp_rmem_min = 4096
net.ipv4.udp_wmem_min = 4096
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_rfc1337 = 1
net.ipv4.tcp_sack = 1
net.ipv4.tcp_ecn = 2
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.all.disable_ipv6 = 0
net.core.netdev_budget_usecs = 5000
net.core.netdev_max_backlog = 65536
net.core.bpf_jit_limit = 1000000000
net.core.netdev_budget = 600
net.core.somaxconn = 8192
